name: b2b_ec_warehouse

profile: b2b_ec_warehouse

# seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  b2b_ec_warehouse:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: staging
      +meta:
        dagster:
          group: staging
    marts:
      +materialized: table
      +schema: marts
      +meta:
        dagster:
          group: marts
